### PR TITLE
Add blacklist to StandardRequestHandler

### PR DESCRIPTION
**Pull request by twam**
Add possibility to pass a blacklist to StandardRequestHandler for packets to ignore, to be able to handle them in a different request handler.

### CODE REVIEW

**Comment by ktemkin** [comment]
This looks pretty good! As a style note, could we:

- Replace the default list with a Tuple? Even though it's not being modified, here, it still feels weird to have a mutable value as a default value.
- Replace the type annotation to something that indicates general iterability / collection-ness, rather than specifying that it should be a list?

**Comment by twam** [comment]
Good points. Adapted accordingly.

**Comment by zyp** [comment]
I can report that I'm successfully using this now to override `SET_INTERFACE`, but there doesn't seem to be a convenient way to pass the blacklist in to the `StandardRequestHandler`?

I've done this in my local working copy:
```diff
diff --git a/luna/gateware/usb/usb2/control.py b/luna/gateware/usb/usb2/control.py
index 713dc21..f35e784 100644
--- a/luna/gateware/usb/usb2/control.py
+++ b/luna/gateware/usb/usb2/control.py
@@ -75,7 +75,7 @@ class USBControlEndpoint(Elaboratable):
         self._request_handlers.append(request_handler)
 
 
-    def add_standard_request_handlers(self, descriptors: DeviceDescriptorCollection):
+    def add_standard_request_handlers(self, descriptors: DeviceDescriptorCollection, **kwargs):
         """ Adds a handlers for the standard USB requests.
 
         This will handle all Standard-type requests; so any additional request handlers
@@ -84,7 +84,7 @@ class USBControlEndpoint(Elaboratable):
         Parameters:
 
         """
-        handler = StandardRequestHandler(descriptors, max_packet_size=self._max_packet_size)
+        handler = StandardRequestHandler(descriptors, max_packet_size=self._max_packet_size, **kwargs)
         self._request_handlers.append(handler)
 
 
diff --git a/luna/gateware/usb/usb2/device.py b/luna/gateware/usb/usb2/device.py
index 052fe3b..6134233 100644
--- a/luna/gateware/usb/usb2/device.py
+++ b/luna/gateware/usb/usb2/device.py
@@ -177,7 +177,7 @@ class USBDevice(Elaboratable):
         return control_endpoint
 
 
-    def add_standard_control_endpoint(self, descriptors: DeviceDescriptorCollection):
+    def add_standard_control_endpoint(self, descriptors: DeviceDescriptorCollection, **kwargs):
         """ Adds a control endpoint with standard request handlers to the device.
 
         Parameters
@@ -192,7 +192,7 @@ class USBDevice(Elaboratable):
 
         # Create our endpoint, and add standard descriptors to it.
         control_endpoint = USBControlEndpoint(utmi=self.utmi)
-        control_endpoint.add_standard_request_handlers(descriptors)
+        control_endpoint.add_standard_request_handlers(descriptors, **kwargs)
         self.add_endpoint(control_endpoint)
 
         return control_endpoint
```

(This also makes the `descriptors` argument redundant and can be folded into `kwargs` if desired.)

It might also be good to be able to add stuff to the blacklist later, e.g. at the same time as you're calling `add_request_handler()` for the handler that's overriding the blacklisted handler.

**Comment by twam** [comment]
I currently just add the handler myself via something like
```
standard_request_handler = StandardRequestHandler(descriptors, blacklist=[lambda setup: (setup.request == USBStandardRequests.SET_INTERFACE)])
self._control_ep.add_request_handler(standard_request_handler)
```
but I also really like your suggestion.

**Comment by twam** [comment]
Rebased on main and added suggestion by @zyp.

**Comment by ktemkin** [comment]
This is looking pretty good -- I'll hopefully give this a quick test in a few hours and then merge it. :)

**Review by ktemkin — CHANGES_REQUESTED** [review]
What's the rationale behind dropping the `descriptors` positional argument, in e.g. `add_standard_request_handlers`? It breaks a bunch of existing code, as `**kwargs` can't accept positional arguments.

Is there any reason not to pass along `descriptors`, too? I'd think if you really have no descriptors (e.g. you're handling `GET_DESCRIPTOR`) elsewhere, it might be better to just pass in `None`, since I think that makes the API clearer.

**Comment by ktemkin** [comment]
Can't merge this without some fixes, since it breaks most of the existing code. I'm willing to do those little fixes, but I want to understand the rationale above first. :)

**Comment by zyp** [comment]
Plain oversight -- I didn't consider `descriptors` could be passed as a positional argument when I made the comment about it being redundant, despite me doing just that in my own code as well.

The rationale for doing the change would be simplification and keeping the API consistent.

**Comment by ktemkin** [comment]
Thanks a ton! Finally merged this in; excuse the rebase noise as we splorked this onto `main`. :)

**Pull request merged**
