### PR TITLE
Reogranize RTD

### PR DESCRIPTION
**Pull request by straithe**
Reorganizes existing LUNA documentation.

### CODE REVIEW

**Comment by mithro** [comment]
You might want to enable read the docs on pull requests so you can preview changes like this. See 
https://docs.readthedocs.io/en/stable/pull-requests.html

**Comment by mithro** [comment]
BTW This reorganization seems to lose a bunch of the useful auto generated class documentation?

**Comment by straithe** [comment]
> BTW This reorganization seems to lose a bunch of the useful auto generated class documentation?

None of the auto-generated content was appearing for me when I build the docs locally on my computer using ```make html```. The content is also not showing up on the Read the Docs page, the autodoc generated content appears as just headers for me. I would love a screenshot or two of useful documentation that was lost.

My goals with this, and all GSG documentation, is to have documentation source material in the repository so anyone can build and view the docs at any time, even if they don't have internet.

**Comment by FFY00** [comment]
That's likely because sphinx can not find the module. This can be fixed in the make file by setting `PYTHONPATH` (see https://github.com/archlinux/svntogit-community/blob/63c09fe1407881a30d5f4a58e7a340cf18753949/trunk/PKGBUILD#L25), and in RTD by installing the project (see https://github.com/pypa/build/blob/main/.readthedocs.yml)

**Pull request closed without merging**
