### PR TITLE
gateware: fix pin assignments and remove deprecated `Case()`

### PR DESCRIPTION
**Pull request by mndza**

### CODE REVIEW

**Review by antoinevg — APPROVED** [review]

**Review by miek — CHANGES_REQUESTED** [review]
This is failing the CI tests: https://github.com/greatscottgadgets/luna/actions/runs/8236675456/job/22523664217#step:5:32

**Comment by antoinevg** [comment]
Lot more coming soon looking at the current pace of commits to @amaranth-lang, @mossmann what is the current status on whether upstream want to contribute effort to bringing the repo up to date?

There's an inflection-point where we'll need to bring the soc stuff up to date to maintain compatibility so it would help if we could synchronize that work.

**Comment by antoinevg** [comment]
> This is failing the CI tests: https://github.com/greatscottgadgets/luna/actions/runs/8236675456/job/22523664217#step:5:32

This is building for me on `amaranth==0.4.1` which _should_ be equivalent to luna's `amaranth~=0.4.0` but I'm probably the last person to ask about pip package resolution.

We're in a weird place, we need a stable pin for cynthion release but there's a lot of things in luna we need for urti and it would be nice to not have to rewrite them when `amaranth>=0.5` comes out. 😛

**Comment by miek** [comment]
> This is building for me on `amaranth==0.4.1` which _should_ be equivalent to luna's `amaranth~=0.4.0` but I'm probably the last person to ask about pip package resolution.

Is that just building a design, or running the tests? That test fails locally for me with amaranth 0.4.1.

**Comment by antoinevg** [comment]
Argh okay, I only ran builds here.

**Comment by miek** [comment]
Thanks!

**Review by miek — APPROVED** [review]

**Review by antoinevg — APPROVED** [review]

**Pull request merged**
