### PR TITLE
 Implement Isochronous OUT Endpoint / Add Examples for USB Audio 2 (Audio + MIDI)

### PR DESCRIPTION
**Pull request by hansfbaier**
The MIDI example works if I restrict it to one output only, otherwise the descriptor would get too large
(see https://github.com/greatscottgadgets/luna/issues/86)

### CODE REVIEW

**Comment by ktemkin** [comment]
Apologies it took me so long to get to this -- I think I must have missed the notification e-mail.

This is awesome work-- though I do have a question. Did you implement `USBIsochronousOutEndpoint` in a missing commit?  At a glance, I don't see an implementation for it. :)

**Comment by hansfbaier** [comment]
Oh.... I just assumed it existed :D
You surely have a point here :)

**Comment by hansfbaier** [comment]
Actually it looks like the Isochronous OUT transaction is the simplest of all. I might give it a a shot and try implementing it.

**Comment by hansfbaier** [comment]
Here is the missing commit :fireworks: :champagne:

**Comment by hansfbaier** [comment]
This PR is now broken because of upstream changes. Will need to rework.

**Pull request closed without merging**
