### PR TITLE
examples/pmod: add nmigen pmod example

### PR DESCRIPTION
**Pull request by TomKeddie**
As per https://github.com/greatscottgadgets/luna/issues/109

### CODE REVIEW

**Comment by ktemkin** [comment]
Example code in general is always good, but I'm not sure this is the right place for this.

Questions:

- Does this belong in the LUNA repository itself? This more seems like an example of using nmigen, rather than an example of anything LUNA-specific. (See the `hw_features` for LUNA-specific examples.)
- Is this a good example of PMOD use, if we do decide yes on the former? I'd prefer examples to be relatively self-contained and to have walkthrough-level documentation (like they would if they were in a minimal tutorial).

**Comment by TomKeddie** [comment]
@ktemkin thanks, I agree but I do think an example showing the pmod connectors in use would be good in luna.  Perhaps an extension of blink that puts the led output through a cable looping pmod A to pmod B?

Alternately I'd be happy to add documentation.  As per https://github.com/greatscottgadgets/luna/issues/72 the examples need a structure within which to document them.

**Comment by TomKeddie** [comment]
@straithe cool, I'm still around.  I passed my luna on to some who had a more immediate need but I'm fine with getting this example into shape as needed.  Thanks for your hard work.

**Comment by miek** [comment]
I'm gonna go ahead and close this as we're moving board-specific components out of this repo. We'll integrate something like this into an example or tutorial as we flesh out the Cynthion documentation. Thanks!

**Pull request closed without merging**
