### PR TITLE
add pip depends support

### PR DESCRIPTION
**Pull request by BracketMaster**
Just a thought, but by adding 
git repositories to ``setup.py``,
downstream projects can simply specify luna
as a dependency, and `pip install` will 
take care of the rest.

Here is an example of a use case I have in mind.
https://github.com/BracketMaster/nmigen-tinyfpgabx/blob/master/requirements.txt#L1

### CODE REVIEW

**Comment by ktemkin** [comment]
Thanks!

As an aside, I probably should drop `pyserial` as a dependency (or make it an optdepend; it's used mostly with examples).

**Comment by ktemkin** [comment]
I remember why I didn't do this originally -- the requirements are viewed as mandatory, and this really messes with providers like ReadTheDocs. Workaround time!

**Comment by BracketMaster** [comment]
oh. welp

**Comment by ktemkin** [comment]
Oh, well -- with a workaround, it should hopefully work well for everyone. :)

https://github.com/greatscottgadgets/luna/blob/master/setup.py#L17

**Comment by BracketMaster** [comment]
Quite clever

**Pull request merged**
